#!/bin/bash
clear
Menu() {
    clear
    echo -e '\n'
    echo "     ==================================="
    echo "                CHANGE DNS (ROOT)     "
   echo "         ==================================="
    echo 
    echo "              ESCOLHA UM DNS"
    echo "        ==================================="
    echo "              [ 1 ] - CloudFire DNS"
    echo "              [ 2 ] - OpenDNS"
    echo "              [ 3 ] - Google DNS"
    echo "              [ 4 ] - Ad Guard DNS"
    echo "              [ 5 ] - DNS Watch"
    echo "              [ 6 ] - GIGA DNS"
    echo "              [ 7 ] - Clean Browsing DNS"
    echo "              [ 8 ] - Quad9 DNS"
    echo "              [ 9 ] - Reverter Alterações"
    echo "              [ 0 ] - DNS Personalizado"
   echo "         ==================================="
    echo 
    echo "ESCOLHA UMA OPÇÃO:"
    read App
    case $App in
    1) d1="1.1.1.1" ; d2="1.0.0.1" ; d3="2606:4700:4700::1111" ; d4="2606:4700:4700::1001" ; d5="1.1.1.1" ; d6="1.0.0.1" ; nome="CloudFire DNS";;
    2) d1="208.67.222.222" ; d2="208.67.220.220" ; d3="2620:119:35::35" ; d4="2620:119:53::53" ; d5="208.67.222.222" ; d6="208.67.220.220" ; nome="OpenDNS" ;;
    3) d1="8.8.8.8" ; d2="8.8.4.4" ; d3="2001:4860:4860::8888" ; d4="2001:4860:4860::8844" ; d5="8.8.8.8" ; d6="8.8.4.4" ; nome="Google Public DNS" ;;
    4) d1="176.103.130.130" ; d2="176.103.130.131" ; d3="2a10:50c0::ad1:ff" ; d4="2a10:50c0::ad2:ff" ; d5="176.103.130.130" ; d6="176.103.130.131" ; nome="Ad Guard DNS";;
    5) d1="84.200.69.80" ; d2="84.200.70.40" ; d3="2001:1608:10:25::1c04:b12f" ; d4="2001:1608:10:25::9249:d69b" ; d5="84.200.69.80" ; d6="84.200.70.40" ; nome="DNS Witch" ;;
    6) d1="189.38.95.95" ; d2="189.38.95.96" ; d3="2804:10:10::10" ; d4="2804:10:10::20" ; d5="189.38.95.95" ; d6="189.38.95.96" ; nome="GIGA DNS";;
    7) d1="185.228.168.9" ; d2="185.228.169.9" ; d3="2a0d:2a00:1::2" ; d4="2a0d:2a00:2::2" ; d5="185.228.168.9" ; d6="185.228.169.9" ; nome="Clean Browsing DNS" ;;
    8) d1="9.9.9.9" ; d2="149.112.112.112" ; d3="2620:fe::fe" ; d4="2620:fe::9" ; d5="9.9.9.9" ; d6="149.112.112.112" ; nome="Quad9 DNS" ;;
    9) App9;;
   0) App0;;
    *) "Calma Barboleta" ; echo ; Menu;;
    esac
    connect
    }

App0(){
clear
 echo -e "ㅤㅤㅤ \emDigite o DNS Primario\em"
read d1
echo
echo -e "ㅤㅤ   \emDigite o DNS Secundario\em"
read d2
echo
echo -e "ㅤ     \emDigite o IPv6 Primario\em"
read d3
echo
echo -e "ㅤ     \emDigite o IPv6 Secundario\em"
read d4
echo ""
connect
}

connect () {
clear
su -c setprop net.dns1 $d1 && su -c setprop net.dns2 $d2 && su -c setprop net.dns3 $d3 && su -c setprop net.dns4 $d4 && su -c setprop net.rmnet0.dns1 $d1 && su -c setprop net.rmnet0.dns2 $d2 && clear && sleep 1 && echo "SEU DNS FOI ALTERADO PARA:" && sleep 1 && echo && echo "    $nome" && sleep 1 && echo && echo "DNS PRIMARIO:" && su -c getprop net.dns1 && sleep 1 && echo && echo "DNS SECUNDARIO:" && su -c getprop net.dns2 && sleep 1 && echo && echo "IPv6 PRIMARIO:" && su -c getprop net.dns3 && sleep 1 && echo && echo "IPv6 SECUNDARIO:" && su -c getprop net.dns4 && echo && sleep 10 && bash force
}
App9(){
clear
su -c settings put global airplane_mode_on 1
su -c am broadcast -a android.intent.action.AIRPLANE_MODE && su -c settings put global airplane_mode_on 0
su -c am broadcast -a android.intent.action.AIRPLANE_MODE && clear
}
clear
Menu
