#!/bin/bash
clear
Menu() {
    clear
    echo -e '\n'
   echo "     ==================================="
    echo "             FORÇAR CONEXÃO (ROOT)     "
   echo "        ==================================="
    echo "                 ESCOLHA UM APP"
    echo
   echo "        ==================================="
    echo "            [ 0 ] - Permições VPN"
    echo "            [ 1 ] - CMSP"
    echo "            [ 2 ] - CMSP KIDS"
    echo "            [ 3 ] - Aulas Parana"
    echo "            [ 4 ] - Conecta Ai"  
    echo "            [ 5 ] - Applique-se"
    echo "            [ 6 ] - Rio Educa Em Casa"  
    echo "            [ 7 ] - Loop De Conexão"
    echo "            [ 8 ] - Change DNS"
   echo "         ==================================="
   echo
    echo "@alpacinoo007"
    echo "@luanw04"
    echo
    echo "Noob Sofre"
    read App
    case $App in  
   1) App="tv.ip.edusp" ; atividade="tv.ip.my.activities.SplashScreen" ; A3="su -c am start -n tv.ip.edusp/tv.ip.my.activities.VideoActivity2 " ; nome="CentroDeMidiasSP" ; A2="su -c am start -n tv.ip.edusp/com.datami.smi.ui.VpnPermissionActivity" ; s="sleep 8" ; A4="su -c am start -n tv.ip.edusp/tv.ip.my.activities.SplashScreen" ; db="su -c pm disable tv.ip.edusp" ; eb="su -c pm enable tv.ip.edusp";;
    2) App="tv.ip.cmspi" ; atividade="tv.ip.my.activities.SplashScreen" ; A3="su -c am start -n tv.ip.cmspi/tv.ip.my.activities.MyVideoActivity" ; nome="RioEducaEmCasa" ; A2="su -c am start -n tv.ip.cmspi/com.datami.smi.ui.VpnPermissionActivity" ; s="sleep 8" ; A4="su -c am start -n tv.ip.cmspi/tv.ip.my.activities.SplashScreen " ; db="su -c pm disable tv.ip.cmspi" ; eb="su -c pm enable tv.ip.cmspi";;
    3) App="tv.ip.aulapr" ; atividade="tv.ip.my.activities.SplashScreen" ; A3="su -c am start -n tv.ip.aulapr/tv.ip.my.activities.VideoActivity2 " ; nome="AulaParana" ; A2="su -c am start -n tv.ip.aulapr/com.datami.smi.ui.VpnPermissionActivity" ; s="sleep 8" ; A4="su -c am start -n tv.ip.aulapr/tv.ip.my.activities.SplashScreen" ; db="su -c pm disable tv.ip.aulapr" ; eb="su -c pm enable tv.ip.aulapr";;
    4) App="tv.ip.conectaai" ; atividade="tv.ip.my.activities.SplashScreen" ; A3="su -c am start -n tv.ip.conectaai/tv.ip.my.activities.MyVideoActivity" ; nome="Applique-se" ; A2="su -c am start -n tv.ip.conectaai/com.datami.smi.ui.VpnPermissionActivity" ; s="sleep 8" ; A4="su -c am start -n tv.ip.conectaai/tv.ip.my.activities.SplashScreen" ; db="su -c pm disable tv.ip.conectaai" ; eb="su -c pm enable tv.ip.conectaai";; 
    5) App="tv.ip.appliquese" ; atividade="tv.ip.my.activities.SplashScreen" ; A3="su -c am start -n tv.ip.appliquese/tv.ip.my.activities.VideoActivity2" ; nome="Applique-se" ; A2="su -c am start -n tv.ip.appliquese/com.datami.smi.ui.VpnPermissionActivity" ; s="sleep 8" ; A4="su -c am start -n tv.ip.appliquese/tv.ip.my.activities.SplashScreen" ; db="su -c pm disable tv.ip.appliquese" ; eb="su -c pm enable tv.ip.appliquese";; 
   6) App="tv.ip.rioeduca" ; atividade="tv.ip.my.activities.SplashScreen" ; A3="su -c am start -n tv.ip.rioeduca/tv.ip.my.activities.VideoActivity2" ; nome="RioEducaEmCasa" ; A2="su -c am start -n tv.ip.rioeduca/com.datami.smi.ui.VpnPermissionActivity" ; s="sleep 8" ; A4="su -c am start -n tv.ip.rioeduca/tv.ip.my.activities.SplashScreen" ; db="su -c pm disable tv.ip.rioeduca" ; eb="su -c pm enable tv.ip.rioeduca";;
    7) App7;;
    8) App8;;
    0) App0;;
    *) "Calma Barboleta" ; echo ; Menu;;
    esac
    connect
    }

App0(){
clear
check1() {
    pervpn=$(test -f "$HOME/PerVPN" && echo 1)
    case $pervpn in
    1) bash PerVPN;;
    *) clear && echo "NECESSARIO TER INTERNET NA 1°" ; echo "VEZ PARA BAIXAR O RECURSO" ; sleep 4 && curl -sO https://raw.githubusercontent.com/luanwillianzh/vpn/main/PerVPN && chmod +x PerVPN && cp PerVPN $PREFIX/bin/ && ./PerVPN ; check1;;
    esac
}
check1
}

App7(){
clear
check4() {
    vpnloop=$(test -f "$HOME/vpn04" && echo 1)
    case $vpnloop in
    1) bash vpn04;;
    *) clear && echo "NECESSARIO TER INTERNET NA 1°" ; echo "VEZ PARA BAIXAR O RECURSO" ; sleep 4 && curl -sO https://raw.githubusercontent.com/luanwillianzh/vpn/main/vpn04 && chmod +x vpn04 && cp vpn04 $PREFIX/bin/ && ./vpn04 ; check4;;
    esac
}
check4
}
App8(){
clear
check1() {
    pervpn=$(test -f "$HOME/changedns2" && echo 1)
    case $pervpn in
    1) bash changedns2;;
    *) clear && echo "NECESSARIO TER INTERNET NA 1°" ; echo "VEZ PARA BAIXAR O RECURSO" ; sleep 4 && curl -sO https://raw.githubusercontent.com/luanwillianzh/vpn/main/changedns2 && chmod +x changedns2 && cp changedns2 $PREFIX/bin/ && ./changedns2 ; check1;;
    esac
}
check1
}

connect () {
clear
su -c am broadcast -p com.applisto.appcloner -a com.applisto.appcloner.api.action.NEW_IDENTITY --es package_name $App [--ez clear_cache {true}] [--ez delete_app_data {true}] && sleep 12 && clear && su -c pm clear $App && su -c am start -n $App/tv.ip.my.activities.PermissionActivity && sleep 1 && su -c am startservice -n $App/tv.ip.my.controller.MyMainService && $A3
check2() {
    vpn=$(ifconfig | grep -c tun0)
    case $vpn in
    0) sleep 2 ; check2;;
    1) su -c am stopservice -n $App/tv.ip.my.controller.MyMainService && su -c killall $App
     esac
}
check2
su -c killall com.termux
}
clear
Menu
