#!/bin/bash
clear
Menu() {
    clear
    echo -e '\n'
   echo "     ==================================="
    echo "                 FORÇAR CONEXÃO  "
   echo "        ==================================="
    echo "                 ESCOLHA UM APP"
    echo
   echo "        ==================================="
    echo "            [ P ] - Permições VPN"
    echo "            [ 1 ] - CMSP"
    echo "            [ 2 ] - CMSP KIDS"
    echo "            [ 3 ] - Aulas Parana"
    echo "            [ 4 ] - Applique-se"
    echo "            [ 5 ] - Rio Educa Em Casa"  
   echo "         ==================================="
   echo
    echo "@alpacinoo007"
    echo "@luanw04"
    echo
    echo "Noob Sofre"
    read App
    case $App in  
   1) App="tv.ip.edusp" ; atividade="tv.ip.my.activities.SplashScreen" ; A3=" am start -n tv.ip.edusp/tv.ip.my.activities.VideoActivity2 " ; nome="CentroDeMidiasSP" ; A2=" am start -n tv.ip.edusp/com.datami.smi.ui.VpnPermissionActivity" ; s="sleep 8" ; A4=" am start -n tv.ip.edusp/tv.ip.my.activities.SplashScreen" ; db=" pm disable tv.ip.edusp" ; eb=" pm enable tv.ip.edusp";;
    2) App="tv.ip.cmspi" ; atividade="tv.ip.my.activities.SplashScreen" ; A3=" am start -n tv.ip.cmspi/tv.ip.my.activities.MyVideoActivity" ; nome="RioEducaEmCasa" ; A2=" am start -n tv.ip.cmspi/com.datami.smi.ui.VpnPermissionActivity" ; s="sleep 8" ; A4=" am start -n tv.ip.cmspi/tv.ip.my.activities.SplashScreen " ; db=" pm disable tv.ip.cmspi" ; eb=" pm enable tv.ip.cmspi";;
    3) App="tv.ip.aulapr" ; atividade="tv.ip.my.activities.SplashScreen" ; A3=" am start -n tv.ip.aulapr/tv.ip.my.activities.VideoActivity2 " ; nome="AulaParana" ; A2=" am start -n tv.ip.aulapr/com.datami.smi.ui.VpnPermissionActivity" ; s="sleep 8" ; A4=" am start -n tv.ip.aulapr/tv.ip.my.activities.SplashScreen" ; db=" pm disable tv.ip.aulapr" ; eb=" pm enable tv.ip.aulapr";; 
    4) App="tv.ip.appliquese" ; atividade="tv.ip.my.activities.SplashScreen" ; A3=" am start -n tv.ip.appliquese/tv.ip.my.activities.VideoActivity2" ; nome="Applique-se" ; A2=" am start -n tv.ip.appliquese/com.datami.smi.ui.VpnPermissionActivity" ; s="sleep 8" ; A4=" am start -n tv.ip.appliquese/tv.ip.my.activities.SplashScreen" ; db=" pm disable tv.ip.appliquese" ; eb=" pm enable tv.ip.appliquese";; 
   5) App="tv.ip.rioeduca" ; atividade="tv.ip.my.activities.SplashScreen" ; A3=" am start -n tv.ip.rioeduca/tv.ip.my.activities.VideoActivity2" ; nome="RioEducaEmCasa" ; A2=" am start -n tv.ip.rioeduca/com.datami.smi.ui.VpnPermissionActivity" ; s="sleep 8" ; A4=" am start -n tv.ip.rioeduca/tv.ip.my.activities.SplashScreen" ; db=" pm disable tv.ip.rioeduca" ; eb=" pm enable tv.ip.rioeduca";;
    P) AppP;;
    p) Appp;;
    *) "Calma Barboleta" ; echo ; Menu;;
    esac
    connect
    }

AppP(){
clear
check1() {
    pervpn=$(test -f "$HOME/PerVPN5" && echo 1)
    case $pervpn in
    1) bash PerVPN5;;
    *) clear && echo "NECESSARIO TER INTERNET NA 1°" ; echo "VEZ PARA BAIXAR O RECURSO" ; sleep 4 && curl -sO https://raw.githubusercontent.com/luanwillianzh/vpn/main/PerVPN5 && chmod +x PerVPN5 && cp PerVPN5 $PREFIX/bin/ && ./PerVPN5 ; check1;;
    esac
}
check1
}

Appp(){
clear
check1() {
    pervpn=$(test -f "$HOME/PerVPN5" && echo 1)
    case $pervpn in
    1) bash PerVPN5;;
    *) clear && echo "NECESSARIO TER INTERNET NA 1°" ; echo "VEZ PARA BAIXAR O RECURSO" ; sleep 4 && curl -sO https://raw.githubusercontent.com/luanwillianzh/vpn/main/PerVPN5 && chmod +x PerVPN5 && cp PerVPN5 $PREFIX/bin/ && ./PerVPN5 ; check1;;
    esac
}
check1
}

connect(){
clear
am start -n $App/tv.ip.my.activities.PermissionActivity && sleep 1 &&  am startservice -n $App/tv.ip.my.controller.MyMainService && $A3
check2() {
    vpn=$(ifconfig | grep -c tun0)
    case $vpn in
    0) sleep 2 ; check2;;
    1)  am stopservice -n $App/tv.ip.my.controller.MyMainService
     esac
}
check2
}
clear
Menu
