#!/bin/bash
clear
Menu() {
echo "    ================================"
    echo "                ID CHANGE   "
   echo "        ================================"   
    echo
    echo "              ESCOLHA UMA OPÇÃO"
    echo "              PARA MUDAR O ID"
   echo "       ================================"
    echo "              [ 1 ] - Escola em Casa DF"
    echo "              [ 2 ] - E-learning EC"
    echo "              [ 3 ] - Educa Olinda"
    echo "              [ 4 ] - Conecta Uneb"
    echo "              [ 5 ] - Sala Estudante SC"
    echo "              [ 6 ] - Minha Estacio"
    echo "              [ 7 ] - Conexão Escola"
    echo "              [ 8 ] - EscoLAR"
    echo "              [ 9 ] - Escola RS - Professor"
    echo "             [ 10 ] - Escola RS - Estudante"
    echo "             [ 11 ] - EDUCA SÃO LEO"
    echo "             [ 12 ] - Estude em Casa"
    echo "             [ 13 ] - Escola MSJ"
    echo "             [ 14 ] - Escola Igarassu"
    echo "             [ 15 ] - Princesa Educa+"
    echo "             [ 16 ] - ConquistApp"
    echo "             [ 17 ] - Net Escola"
    echo "             [ 18 ] - CMSP"
    echo "             [ 19 ] - CMSP KIDS"
    echo "             [ 20 ] - Aulas Parana"
    echo "             [ 21 ] - Conecta Ai"  
    echo "             [ 22 ] - Applique-se"
    echo "             [ 23 ] - Rio Educa Em Casa"  
   echo "       ================================"
    echo "@luanw04"
    echo "@alpacinoo007"
    echo 
    echo "ESCOLHA UMA OPÇÃO:"
    read App
    case $App in
    1) App="org.cordova.quasar.corona.app" ; atividade=".SplashScreenActivity" ; nome="EscolaEmCasaDF" ; E1="sleep 10";;
    2) App="com.portoseguru.reach4all" ; atividade="com.datami.reachall.SplashScreen" ; nome="E-learningEC" ; E1="sleep 10";;
    3) App="org.educaolinda.app" ; atividade="org.aprendendosempre.app.main.MainActivity" ; nome="EducaOlinda" ; E1="sleep 10";;   
    4) App="com.conectauneb.reach4all" ; atividade="com.datami.reachall.SplashScreen" ; nome="ConectaUneb" ; E1="sleep 10";;   
    5) App="br.sc.gov.ciasc.sed.inp" ; atividade=".MainActivity" ; nome="SalaEstudanteSC" ; E1="sleep 10";;
    6) App="br.estacio.estaciomobile" ; atividade="br.estacio.mobile.MainActivity" ; nome="MinhaEstacio" ; E1="sleep 10";;
    7) App="br.gov.prodemge.conexaoescola" ; atividade=".SplashActivity" ; nome="ConexãoEscola" ; E1="sleep 10";;
    8) App="br.gov.es.sedu.educacao" ; atividade=".MenuActivity" ; nome="EscoLAR" ; E1="sleep 10";;
    9) App="br.com.procergs.tuaescola" ; atividade=".MainActivity" ; nome="EscolaProfessorRS" ; E1="sleep 10";;
    10) App="br.com.procergs.estudante" ; atividade=".MainActivity" ; nome="EscolaEstudanteRS" ; E1="sleep 10";;
    11) App="com.educasaoleo.reach4all" ; atividade="com.educasaoleo.reachall.SplashScreen" ; nome="EducaSãoLeo" ; E1="sleep 10";;
    12) App="com.seduc.estudeemcasa" ; atividade=".SplashActivity" ; nome="EstudeEmCasa" ; E1="sleep 10";;
    13) App="com.escola.msj" ; atividade=".SplashScreenActivity" ; nome="EscolaMSJ" ; E1="sleep 10";;
    14) App="org.educarigarassu.app" ; atividade=".SplashScreenActivity" ; nome="EscolaIgarassu" ; E1="sleep 10";;
    15) App="com.princesaeducamais" ; atividade=".SplashActivity" ; nome="PrincesaEduca+" ;;
    16) App="br.gov.ba.pmvc.vcapp" ; atividade=".SplashScreenActivity" ; nome="ConquistApp" ; E1="sleep 10";;    
    17) App="br.gov.go.seduc.netescola" ; atividade="br.gov.go.seduc.netescola.MainActivity" ; nome="NetEscola" ;;
   18) App="tv.ip.edusp" ; atividade="tv.ip.my.activities.SplashScreen" ; A3="su -c am start -n tv.ip.edusp/tv.ip.my.activities.VideoActivity2 " ; nome="CentroDeMidiasSP" ; A2="su -c am start -n tv.ip.edusp/com.datami.smi.ui.VpnPermissionActivity" ; s="sleep 8" ; A4="su -c am start -n tv.ip.edusp/tv.ip.my.activities.SplashScreen" ; db="su -c pm disable tv.ip.edusp" ; eb="su -c pm enable tv.ip.edusp";;
    19) App="tv.ip.cmspi" ; atividade="tv.ip.my.activities.SplashScreen" ; A3="su -c am start -n tv.ip.cmspi/tv.ip.my.activities.MyVideoActivity" ; nome="RioEducaEmCasa" ; A2="su -c am start -n tv.ip.cmspi/com.datami.smi.ui.VpnPermissionActivity" ; s="sleep 8" ; A4="su -c am start -n tv.ip.cmspi/tv.ip.my.activities.SplashScreen " ; db="su -c pm disable tv.ip.cmspi" ; eb="su -c pm enable tv.ip.cmspi";;
    20) App="tv.ip.aulapr" ; atividade="tv.ip.my.activities.SplashScreen" ; A3="su -c am start -n tv.ip.aulapr/tv.ip.my.activities.VideoActivity2 " ; nome="AulaParana" ; A2="su -c am start -n tv.ip.aulapr/com.datami.smi.ui.VpnPermissionActivity" ; s="sleep 8" ; A4="su -c am start -n tv.ip.aulapr/tv.ip.my.activities.SplashScreen" ; db="su -c pm disable tv.ip.aulapr" ; eb="su -c pm enable tv.ip.aulapr";;
    21) App="tv.ip.conectaai" ; atividade="tv.ip.my.activities.SplashScreen" ; A3="su -c am start -n tv.ip.conectaai/tv.ip.my.activities.MyVideoActivity" ; nome="Applique-se" ; A2="su -c am start -n tv.ip.conectaai/com.datami.smi.ui.VpnPermissionActivity" ; s="sleep 8" ; A4="su -c am start -n tv.ip.conectaai/tv.ip.my.activities.SplashScreen" ; db="su -c pm disable tv.ip.conectaai" ; eb="su -c pm enable tv.ip.conectaai";; 
    22) App="tv.ip.appliquese" ; atividade="tv.ip.my.activities.SplashScreen" ; A3="su -c am start -n tv.ip.appliquese/tv.ip.my.activities.VideoActivity2" ; nome="Applique-se" ; A2="su -c am start -n tv.ip.appliquese/com.datami.smi.ui.VpnPermissionActivity" ; s="sleep 8" ; A4="su -c am start -n tv.ip.appliquese/tv.ip.my.activities.SplashScreen" ; db="su -c pm disable tv.ip.appliquese" ; eb="su -c pm enable tv.ip.appliquese";; 
   23) App="tv.ip.rioeduca" ; atividade="tv.ip.my.activities.SplashScreen" ; A3="su -c am start -n tv.ip.rioeduca/tv.ip.my.activities.VideoActivity2" ; nome="RioEducaEmCasa" ; A2="su -c am start -n tv.ip.rioeduca/com.datami.smi.ui.VpnPermissionActivity" ; s="sleep 8" ; A4="su -c am start -n tv.ip.rioeduca/tv.ip.my.activities.SplashScreen" ; db="su -c pm disable tv.ip.rioeduca" ; eb="su -c pm enable tv.ip.rioeduca";;
    *) "Calma Barboleta" ; echo ; Menu;;
    esac
    connect
    }

connect () {
clear
am broadcast -p com.applisto.appcloner -a com.applisto.appcloner.api.action.NEW_IDENTITY --es package_name $App [--ez clear_cache {true}] [--ez delete_app_data {true}] && clear && sleep 8 && echo "LIMPE OS DADOS E ENTRE NO APP"
check1() {
    vpn=$(ifconfig | grep -c tun0)
    case $vpn in
    1) clear ;;
    0) sleep 2 ; check1;;
    esac
}
check1
check2() {
    vpn=$(ifconfig | grep -c tun0)
    case $vpn in
    1) sleep 2 ; check2 ;;
    0) am start -n com.termux/com.termux.HomeActivity && clear ; connect;;
    esac
}
check2
}
clear
Menu
