#!/bin/bash
clear
Menu() {
echo "    ================================"
    echo "                 ID ILIMITADO     "
   echo "        ================================"   
    echo
    echo "               ESCOLHA UMA OPÇÃO"
   echo "       ================================"
    echo "            [ 1 ] - EscolaEmCasaDF"
    echo "            [ 2 ] - E-learningEC"
    echo "            [ 3 ] - EducaOlinda"
    echo "            [ 4 ] - ConectaUneb"
    echo "            [ 5 ] - SalaEstudanteSC"
    echo "            [ 6 ] - MinhaEstacio"
    echo "            [ 7 ] - ConexãoEscola"
    echo "            [ 8 ] - EscoLAR"
    echo "            [ 9 ] - EscolaProfessorRS"
    echo "           [ 10 ] - EscolaEstudanteRS"
    echo "           [ 11 ] - EducaSãoLeo"
    echo "           [ 12 ] - EstudeEmCasa"
    echo "           [ 13 ] - EscolaMSJ"
    echo "           [ 14 ] - EscolaIgarassu"
    echo "           [ 15 ] - PrincesaEduca+"
    echo "           [ 16 ] - ConquistApp"
   echo "       ================================"
    echo "@luanw04"
    echo "@alpacinoo007"
    echo 
    echo "ESCOLHA UMA OPÇÃO:"
    read App
    case $App in
    1) App="org.cordova.quasar.corona.app" ; atividade=".SplashScreenActivity" ; nome="EscolaEmCasaDF" ; E1="sleep 10";;
    2) App="com.portoseguru.reach4all" ; atividade="com.datami.reachall.SplashScreen" ; nome="E-learningEC" ; E1="sleep 10";;
    3) App="org.educaolinda.app" ; atividade="org.aprendendosempre.app.main.MainActivity" ; nome="EducaOlinda" ; E1="sleep 10";;   
    5) App="br.sc.gov.ciasc.sed.inp" ; atividade=".MainActivity" ; nome="SalaEstudanteSC" ; E1="sleep 10";;
    6) App="br.estacio.estaciomobile" ; atividade="br.estacio.mobile.MainActivity" ; nome="MinhaEstacio" ; E1="sleep 10";;
    7) App="br.gov.prodemge.conexaoescola" ; atividade=".SplashActivity" ; nome="ConexãoEscola" ; E1="sleep 10";;
    8) App="br.gov.es.sedu.educacao" ; atividade=".MenuActivity" ; nome="EscoLAR" ; E1="sleep 10";;
    9) App="br.com.procergs.tuaescola" ; atividade=".MainActivity" ; nome="EscolaProfessorRS" ; E1="sleep 10";;
    10) App="br.com.procergs.estudante" ; atividade=".MainActivity" ; nome="EscolaEstudanteRS" ; E1="sleep 10";;
    11) App="com.educasaoleo.reach4all" ; atividade="com.educasaoleo.reachall.SplashScreen" ; nome="EducaSãoLeo" ; E1="sleep 10";;
    12) App="com.seduc.estudeemcasa" ; atividade=".SplashActivity" ; nome="EstudeEmCasa" ; E1="sleep 10";;
    13) App="com.escola.msj" ; atividade=".SplashScreenActivity" ; nome="EscolaMSJ" ; E1="sleep 10";;
    14) App="org.educarigarassu.app" ; atividade=".SplashScreenActivity" ; nome="EscolaIgarassu" ; E1="sleep 10";;
    15) App="com.princesaeducamais" ; atividade=".SplashActivity" ; nome="PrincesaEduca+" ;;
    16) App="br.gov.ba.pmvc.vcapp" ; atividade=".SplashScreenActivity" ; nome="ConquistApp" ; E1="sleep 10";;    
    *) "Calma Barboleta" ; echo ; Menu;;
    esac
    connect
    }

connect () {
clear
check6(){
      apps=$(test -d "/data/data/$App" && echo 1)
    case $apps in
     1) clear ;;
     *) echo "INSTALANDO..." ; echo "NÃO FAÇA NADA!" ; sleep 3 && termux-open --chooser /storage/emulated/0/Download/$nome.apk ;;
     esac
}
check6
check7(){
      apps=$(test -d "/data/data/$App" && echo 1)
    case $apps in
     1) clear ;;
     *) sleep 2 ; check7 ;;
     esac
}
check7
am start -n $App/$atividade 
check1() {
    vpn=$(ifconfig | grep -c tun0)
    case $vpn in
    1) clear;;
    0) sleep 2 ; check1;; 
    esac
}
check1
check2() {
    vpn=$(ifconfig | grep -c tun0)
    case $vpn in
    1) sleep 2 ; check2 ;;
    0) clear ;;
    esac
}
check2
am start -n com.termux/com.termux.HomeActivity && clear && echo "AGORA DESINSTALE O APP"
check3(){
      Appss=$(test -d "/data/data/$App" && echo 1)
    case $Appss in
     1) sleep 2 ; check3 ;;
     *) clear;;
     esac
}
check3
am start -n com.termux/com.termux.HomeActivity && clear && echo "INSTALANDO NOVAMENTE..." ; echo "NÃO FAÇA NADA!" ; termux-open --chooser /storage/emulated/0/Download/$nome.apk
check4(){
      apps=$(test -d "/data/data/$App" && echo 1)
    case $apps in
     1) connect ;;
     *) sleep 2 ; check4 ;;
     esac
}
check4
}
clear
Menu
