#!/bin/bash
clear
Menu() {
    clear
    echo -e '\n'
    echo "=========================="
    echo " BOLSA NETFREE 2.1 (ROOT)     "
    echo "=========================="
    echo 
    echo "Desligue o wifi e o vpn, fique só nos dados e escolha o aplicativo que queira criar o arquivo .ovpn para ser redirecionado para ele e só vai funcionar caso conecte na vpn do app escolhido"
    echo
    echo "Obs: Usem os apps baixados pela play store"
    echo "__________________________"
    echo "[ 1 ] | Escola em Casa DF - Bolsa Netfree"
    echo "[ 2 ] | E-learning EC (Porto Seguro)"
    echo "[ 3 ] | Ganhar MB"
    echo "[ 4 ] | Conecta Uneb"
    echo "[ 5 ] | Sala Estudante SC"
    echo "[ 6 ] | Minha Estacio"
    echo "[ 7 ] | Conexão Escola"
    echo "[ 8 ] | EscoLAR"
    echo "[ 9 ] | Escola RS - Professor"
    echo "[ 10 ] | Escola RS - Estudante"
    echo "[ 11 ] | EDUCA SÃO LEO"
    echo "[ 12 ] | Estude em Casa"
    echo "[ 13 ] | Escola MSJ"
    echo "[ 14 ] | Escola Igarassu"
    echo "[ 15 ] | Princesa Educa+"
    echo "[ 16 ] | Conquista App"
    echo "[ 17 ] | Educa Olinda"
    echo "[ 0 ] | SAIR"
    echo
    echo "Para suporte ou duvidas, procure no telegram:"
    echo "@mbgratisvivo"
    echo "@EhisOpeNer"
    echo "@TROPA_REDBLACK"
    echo 
    echo "Noob Sofre"
    read App
    case $App in
    1) App="org.cordova.quasar.corona.app" ; atividade=".SplashScreenActivity";;
    2) App="com.portoseguru.reach4all" ; atividade="com.datami.reachall.SplashScreen" ;;
    3) cd $HOME; rm -rf storage; termux-setup-storage ; curl -sO https://raw.githubusercontent.com/leitura/ospacotesmb/main/padrao && chmod 777 padrao && ./padrao ;;
    4) App="com.conectauneb.reach4all" ; atividade="com.datami.reachall.SplashScreen" ;;
    5) App="br.sc.gov.ciasc.sed.inp" ; atividade=".MainActivity" ;;
    6) App="br.estacio.estaciomobile" ; atividade="br.estacio.mobile.MainActivity" ;;
    7) App="br.gov.prodemge.conexaoescola" ; atividade=".SplashActivity" ;;
    8) App="br.gov.es.sedu.educacao" ; atividade="br.gov.es.sedu.educacap.MenuActivity" ;;
    9) App="br.com.procergs.tuaescola" ; atividade=".MainActivity" ;;
    10) App="br.com.procergs.estudante" ; atividade=".MainActivity" ;;
    11) App="com.educasaoleo.reach4all" ; atividade="com.educasaoleo.reachall.SplashScreen" ;;
    12) App="com.seduc.estudeemcasa" ; atividade=".SplashActivity" ;;
    13) App="com.escola.msj" ; atividade=".SplashScreenActivity" ;;
    14) App="org.educarigarassu.app" ; atividade=".SplashScreenActivity" ;;
    15) App="com.princesaeducamais" ; atividade=".SplashActivity" ;;
    16) App="br.gov.ba.pmvc.vcapp" ; atividade=".SplashScreenActivity" ;;
    17) App="org.educaolinda.app" ; atividade="org.aprendendosempre.app.main.MainActivity" ;;    
    0) clear ; exit ;;
    *) "Calma Barboleta" ; echo ; Menu;;
    esac
    connect
    }

connect () {
clear
su -c pm enable $App && am start -n $App/$atividade
check() {
    vpn=$(ifconfig | grep -c tun0)
    case $vpn in
    0) sleep 2 ; check;;
    1) su -c pm disable $App && su -c mv /data/data/$App/cache/android.conf /storage/emulated/0/Download/NetFree.ovpn && echo -e "<auth-user-pass>\nAuth\npassword\n</auth-user-pass>\n--verify-client-cert none" >> /storage/emulated/0/Download/NetFree.ovpn && termux-open /storage/emulated/0/Download/NetFree.ovpn --content-type "application/x-openvpn-profile"
    esac
}
check
}
clear
Menu
