#!/bin/bash
clear
Menu() {
    clear
    echo -e '\n'
    echo "=========================="
    echo " BOLSA NETFREE 3.0 (ROOT)     "
    echo "=========================="
    echo 
    echo "Apenas desconecte da vpn caso esteja conectado"
    echo "e escolha o app de escola que deseja gerar"
    echo "o arquivo .ovpn"
    echo
    echo "Obs: Usem os apps baixados pela play store"
    echo "__________________________"
    echo "[ 1 ] | Escola em Casa DF"
    echo "[ 2 ] | E-learning EC"
    echo "[ 3 ] | Educa Olinda"
    echo "[ 4 ] | Conecta Uneb"
    echo "[ 5 ] | Sala Estudante SC"
    echo "[ 6 ] | Minha Estacio"
    echo "[ 7 ] | Conexão Escola"
    echo "[ 8 ] | EscoLAR"
    echo "[ 9 ] | Escola RS - Professor"
    echo "[ 10 ] | Escola RS - Estudante"
    echo "[ 11 ] | EDUCA SÃO LEO"
    echo "[ 12 ] | Estude em Casa"
    echo "[ 13 ] | Escola MSJ"
    echo "[ 14 ] | Escola Igarassu"
    echo "[ 15 ] | Princesa Educa+"
    echo "[ 16 ] | ConquistApp"
    echo "[ 0 ] | SAIR"
    echo
    echo "Para suporte ou duvidas, procure no telegram:"
    echo "@mbgratisvivo"
    echo "@EhisOpeNer"
    echo "@TROPA_REDBLACK"
    echo
    echo "Script feito por @alpacinoo007 e @luanw04"
    echo 
    echo "Noob Sofre"
    read App
    case $App in
    1) App="org.cordova.quasar.corona.app" ; atividade=".SplashScreenActivity" ; nome="EscolaDF" ;;
    2) App="com.portoseguru.reach4all" ; atividade="com.datami.reachall.SplashScreen" ; nome="E-learning" ;;
    3) App="org.educaolinda.app" ; atividade="org.aprendendosempre.app.main.MainActivity" ; nome="EducaOlinda" ;;   
    4) App="com.conectauneb.reach4all" ; atividade="com.datami.reachall.SplashScreen" ; nome="ConectaUneb" ;;
    5) App="br.sc.gov.ciasc.sed.inp" ; atividade=".MainActivity" ; nome="SalaEstudanteSC" ;;
    6) App="br.estacio.estaciomobile" ; atividade="br.estacio.mobile.MainActivity" ; nome="MinhaEstacio" ;;
    7) App="br.gov.prodemge.conexaoescola" ; atividade=".SplashActivity" ; nome="ConexaoEscola" ;;
    8) App="br.gov.es.sedu.educacao" ; atividade=".MenuActivity" ; nome="EscoLAR" ;;
    9) App="br.com.procergs.tuaescola" ; atividade=".MainActivity" ; nome="EscolaProfessorRS" ;;
    10) App="br.com.procergs.estudante" ; atividade=".MainActivity" ; nome="EscolaEstudanteRS" ;;
    11) App="com.educasaoleo.reach4all" ; atividade="com.educasaoleo.reachall.SplashScreen" ; nome="EducaSãoLeo" ;;
    12) App="com.seduc.estudeemcasa" ; atividade=".SplashActivity" ; nome="EstudeEmCasa" ;;
    13) App="com.escola.msj" ; atividade=".SplashScreenActivity" ; nome="EscolaMSJ" ;;
    14) App="org.educarigarassu.app" ; atividade=".SplashScreenActivity" ; nome="EducarIguarassu" ;;
    15) App="com.princesaeducamais" ; atividade=".SplashActivity" ; nome="PrincesaEducaMais" ;;
    16) App="br.gov.ba.pmvc.vcapp" ; atividade=".SplashScreenActivity" ; nome="ConquistApp" ;;    
    0) clear ; exit ;;
    *) "Calma Barboleta" ; echo ; Menu;;
    esac
    connect
    }

connect () {
clear
su -c settings put global airplane_mode_on 1
su -c am broadcast -a android.intent.action.AIRPLANE_MODE && su -c settings put global airplane_mode_on 0
su -c am broadcast -a android.intent.action.AIRPLANE_MODE && su -c 'svc wifi disable' && su -c 'svc data enable' && su -c pm enable $App && su -c pm clear $App && clear
  check() {
    dados=$(ifconfig | grep -c rmnet0)
    case $dados in
    0) sleep 2 ; check;;
    1) am start -n $App/$atividade && clear ;;
     esac
}
check
check() {
    vpn=$(ifconfig | grep -c tun0)
    case $vpn in
    0) sleep 2 ; check;;
    1) su -c pm disable $App && su -c mv /data/data/$App/cache/android.conf /storage/emulated/0/Download/$nome.ovpn && su -c pm clear $App && echo -e "<auth-user-pass>\nAuth\npassword\n</auth-user-pass>\n--verify-client-cert none" >> /storage/emulated/0/Download/$nome.ovpn && termux-open /storage/emulated/0/Download/$nome.ovpn --content-type "application/x-openvpn-profile"
    esac
}
check
check() {
    vpn=$(ifconfig | grep -c tun0)
    case $vpn in
    0) sleep 2 ; check;;
    1) su -c setprop net.dns1 1.1.1.1 && su -c setprop net.dns2 1.0.0.1 && su -c setprop net.dns3 2606:4700:4700::1111 && su -c setprop net.dns4 2606:4700:4700::1001 && su -c setprop net.rmnet0.dns1 1.1.1.1 && su -c setprop net.rmnet0.dns2 1.0.0.1;;
     esac
}
check
}
clear
Menu
