#!/bin/bash

clear
Porra(){
VermelhoAll='\e[01;37;41m'
NADA='\033[0m'
CINZA='\e[02;37m'
DESTACAR='\e[01;37m'
RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
SCOLOR='\033[0m'
SEMCOR='\033[8m'

termux-wake-lock

rm -f ipcasa.txt
rm -f Proxy443.txt

clear
echo -e "${DESTACAR}ESSE SCRIPT SERVE PARA TESTAR PROXYS NA PORTA 443"
echo
echo -e "FUNCIONA COM 2 OU 3 CASAS, EX: 104.10. OU 104.10.10. ${NADA}"
echo
read -p "DOMINIO: " dominio
echo
read -p "IP: " ip
echo
dots=$(fgrep "." -o <<< $ip | wc -l)
case $dots in
  2)DuasCasas;;                                        3)Trescasas;;
  *)Porra;;
  esac
}


DuasCasas(){
echo -e "1" >> ipcasa.txt
for i in $(seq 255)
do
GRISS=$(cat ipcasa.txt | grep -c 1)
rm -f LogsProxyTest.txt

testeproxy=$(curl -s -m 0.1 --connect-to $dominio:443:$ip$GRISS.$i:443 https://$dominio/ -vs >LogsProxyTest.txt 2>&1)

test=$(cat LogsProxyTest.txt | grep -c "Connected")
case $test in
1) echo -e "${YELLOW}$ip$GRISS.$i ${NADA}| ${GREEN}TRUE${NADA}"; echo -e "$ip$GRISS.$i | TRUE" >> True.txt ;;
0) echo -e "${YELLOW}$ip$GRISS.$i ${NADA}| ${RED}FALSE${NADA}";;
esac
done
echo
cat True.txt
echo

DuasCasas
}


Trescasas(){
for i in $(seq 255)
do
rm -f LogsProxyTest.txt
testeproxy=$(curl -s -m 0.1 --connect-to $dominio:443:$ip$i:443 https://$dominio/ -vs >LogsProxyTest.txt 2>&1)

test=$(cat LogsProxyTest.txt | grep -c "Connected")
case $test in
1) echo -e "${YELLOW}$ip$i${NADA} | ${GREEN}TRUE${NADA}" ; echo -e "$ip$i | TRUE" >> True.txt;;
0) echo -e "${YELLOW}$ip$i${NADA} | ${RED}FALSE${NADA}";;
esac
done
echo
cat True.txt
}

Porra
